name: integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:

  # Publish NPM package
  publish:
    name: Publish NPM package
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
        # id-token: write permission is required for npm provenance:
        # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
        id-token: write
        # contents: write is required for git push
        contents: write
    steps:

      - uses: actions/checkout@v4
        with:
          # fetch all branches
          fetch-depth: 0

      # Configure git user for later command induced commits
      - uses: fregante/setup-git-user@v1

      - uses: actions/setup-node@v4
        with:
          node-version: 22.17
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run prepare

      - name: publish itowns@latest npm package
        run: |
          npm version minor -m \"release v%s\"
          git push
          npm run publish-latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

